INSERT INTO category(DESCRIPTION) VALUES('American');
INSERT INTO category(DESCRIPTION) VALUES('Italian');
INSERT INTO category(DESCRIPTION) VALUES('Mexican');
INSERT INTO category(DESCRIPTION) VALUES('Fast Food');
INSERT INTO Unit_of_Measure (description) values('Teaspoon');
INSERT INTO Unit_of_Measure (description) values('Tablespoon');
INSERT INTO Unit_of_Measure (description) values('Cup');
INSERT INTO Unit_of_Measure (description) values('Pinch');
INSERT INTO Unit_of_Measure (description) values('Ounce');
INSERT INTO unit_of_measure (description) VALUES ('Each');
INSERT INTO unit_of_measure (description) VALUES ('Dash');
INSERT INTO unit_of_measure (description) VALUES ('Pint');